version: "2.1"

services:

  zookeeper:
    #build: .
    image: 'deployable/kafka:latest'
    command: zookeeper
    ports:
     - "2182:2181"
    networks:
     - etc
    healthcheck:
      test: [ "CMD", "/kafka/check.sh", "zookeeper" ]
      interval: 30s
      timeout: 5s
      retries: 3

  kafka:
    ##build: .
    image: 'deployable/kafka:latest'
    command: kafka
    environment:
      ADVERTISE_LISTENERS: '10.8.8.8:9093'
    ports:
     - "9093:9092"
    networks:
     - etc
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "/kafka/check.sh", "kafka" ]
      interval: 30s
      timeout: 5s
      retries: 3


  kafka-setup:
    ##build: .
    image: 'deployable/kafka:latest'
    command: setup
    networks:
     - etc
    depends_on:
      - kafka
    environment:
      KAFKA_TOPIC: my-test-topic

networks:
  etc:
    driver: bridge

